version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mobile-net

  nestjs:
    image: 528192012668.dkr.ecr.ap-southeast-1.amazonaws.com/mobile-app-backend:latest
    env_file:
      - .env.prod
    ports:
      - "80:8080"
    depends_on:
      - postgres
    networks:
      - mobile-net
    deploy:
      resources:
        limits:
          memory: 512M   # Giới hạn RAM tối đa 512MB
          cpus: "0.50"   # Chỉ dùng tối đa nửa CPU

volumes:
  pgdata:

networks:
  mobile-net:
    driver: bridge
