services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mobile-net   # 👈 gán vào mạng riêng

  nestjs:
    image: ${ECR_REPOSITORY}:latest
    restart: always
    env_file:
      - .env.prod
    ports:
      - "80:8080"
    depends_on:
      - postgres
    networks:
      - mobile-net   # 👈 cùng mạng với postgres

volumes:
  pgdata:

networks:
  mobile-net:       # 👈 network kiểu bridge
    driver: bridge
